sudo: required
services:
    - docker

before_install:
  - docker build -t jklegseth/docker-react -f Dockerfile.dev .

script:
  - docker run jklegseth/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-438021297134"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
      secure: "$AWS_SECRET_KEY"